# Welcome to Lab: Similarity 🧍🧍‍♂️🧍‍♀️

Many of you already know your group members in this class. However, have you ever wondered if there is someone **even more similar** to you than the people you already know?

In this lab, we'll once again explore the dataset from the **Hello Survey** you've completed, utilizing some new Python skills to calculate your similarity to your peers!

A few tips to remember:

- **You are not alone on your journey in learning programming!**  You have your lab TA, your CAs, your lab group, and the professors (Prof. Wade and Prof. Karle), who are all here to help you out!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

In [50]:
# Meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Kunlun"
ca1_name = "Emily"
ca2_name = "Caroline"
ca3_name = ""


# Say hello to each other!
# - Groups of 3 are ideal :)
# - However, groups of 2 or 4 are fine too!

# QOTD to ask your group: What's your favorite (or least favorite) building on campus? 
partner1_name = "Xinmeng Zhang"
partner1_netid = "xinmeng8"
partner1_favbuilding = "Illini Tower"

partner2_name = "Miguel Jaojoco"
partner1_netid = "jaojoco2"
partner2_favbuilding = "Main Quad"

partner3_name = ""
partner3_netid = ""
partner3_favbuilding = ""

# Which lab section are you in? Record it below! It should start with a Y and have 
# 2 numbers after the Y. If you're unsure - ask your TA/CAs!
lab_section = "Y27"

<hr style="color: #DD3403;">

# Part 1: Hello, Again

## Load the Hello Dataset
To find the people most similar to you in this course, we're going to need the Hello Dataset again.


The "Hello Dataset" is available here:
```
https://waf.cs.illinois.edu/discovery/hello-fa25.csv
```

Use Python to load this dataset into a DataFrame `df`:

In [51]:
import pandas as pd
df=pd.read_csv("https://waf.cs.illinois.edu/discovery/hello-fa25.csv")
df

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
0,Prof. Wade,AL1,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Sweeden,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin
1,Prof. Karle,AL1,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Maldives,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives
2,Muhammad,Y20,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Malaysia,Green,Sleeping,Hip hop,Husky,Electrical Engineering,Kanye West,Instagram,Minecraft,Switzerland
3,Jake,Y10,Heads,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Norway,Yellow,Hang Out With Friends,Indie Music,Llama,Electrical Engineering,Tame Impala,Instagram,Volleyball,Switzerland Alps
4,Shourya,Y04,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,UAE,Red,Youtube,Indie pop,Wolf,Astrophysics,Cigarettes after sex,Instagram,Spy,Iceland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,arnav,Y31,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,Movies,...,Singapore,Blue,Hang out with friends,R&b,Lion,Chemical engineering,NaN,Instagram,NaN,Indonesia
1196,Lorenzo,Y11,Heads,Chocolate,Morning,Even,Yes,Summer,In Gies College of Business,Movies,...,Canada,blue,sleep,jazz,dog,cs,MBY,wechat,MC,Canada
1197,CA Emma,Y20,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Sweden,Green,Crocheting,Pop,Frog,Computer Science,Lady Gaga,TikTok,Minecraft,Italy
1198,CA Soph,Y01 Y14 Y15 Y18,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Mexico,Red,Relaxing,Hyperpop,Rabbit,Aerospace Engineering,Ayesha Erotica,Pinterest,Twister,Mexico City
1199,Jay,Y07,Tails,Vanilla,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Paris,Blue,On Tiktok,R&B,Wolf,Chem E,Mac Demarco,TikTok,Basketball,Hawaii

### 🔬 Test Case Checkpoint 🔬

In [52]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert("df" in vars()), "This is not the Hello Dataset you're looking for. Check the URL."
assert("Where is your dream vacation spot?" in df), "This is not the Hello Dataset you're looking for. Check the URL."
assert(len(df) >= 1140), "This is not the Hello Dataset you're looking for. Check the URL."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Finding Yourself
Before finding people you are **similar to**, you have to find **yourself** - literally!

### Puzzle 1.1: Your Row
In the following cell, write the Python code to create a **new** DataFrame with only yourself, named `df_me`, and then display it.

*Note: if you cannot find yourself in the Hello Dataset, try adding a space after your name within the string. If you did not fill out the Hello Survey, pick one of your TAs, CAs, or Professor Karle or Wade! Their names are in the survey in the format of "TA Alex" or "Prof. Karle".*

In [53]:
df_me = df[df["Name"] == "yes！"]
df_me

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
485,yes！,Y27,Heads,Chocolate,Morning,Even,Yes,Winter,Not in Gies,TV Shows,...,China,gray,play mobile game,Jazz,Panda,Math+CS,My roommate,WeChat,Honor of King,New zealand

### 🔬 Test Case Checkpoint 🔬

In [54]:
## == PUZZLE 1.1 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert("df_me" in vars()), "Make sure you named the DataFrame with just you `df_me`."
assert("Where is your dream vacation spot?" in df_me), "Your `df_me` should have the same columns as our `df`."
assert(len(df_me.columns.to_list()) == 160), "Your `df_me` should have the same number of columns as our original `df`."
assert(len(df_me) == 1), "Your `df_me` should only have one row: yourself."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## DataFrame vs. Series

In `pandas`, we have worked with **DataFrames** all semester long! DataFrames are similar to excel sheets and have rows and columns with data!

Another data type is called a **Series**.

- A **Series** is a single row with zero or more values (columns). You can think of a DataFrame as a collection of **Series** objects. When we deal with a single row, we will usually want to deal with a **Series** instead of a **one row DataFrame**

In this lab, we will learn how to convert from a **one row DataFrame** to a **Series**, but here's a quick rundown on how to convert from types:

### Converting Types

The `pandas` library makes it easy to convert between a **Series** and a **DataFrame**.

- From a **Series** (`row`) to a **DataFrame**:
    - `row.to_frame()`
- From a **DataFrame** (`df`) to a **Series**:
    - `df.iloc[0]`, if the DataFrame has one row

See this guide, https://discovery.cs.illinois.edu/guides/DataFrame-Fundamentals/dataframe-loc-vs-iloc/, for more information about `iloc[]`.

### Puzzle 1.2: Transform your row into a Series
Using the correct function from above, **transform** the `df_me` row containing only you from a **one-row DataFrame** into a **Series**. 

Make sure the Series is named `my_row` (this will match up with code we provide you with later):

In [55]:
my_row = df_me.iloc[0]
my_row

Name                                                                       yes！
Lab                                                                         Y27
When flipping a coin, heads or tails?                                     Heads
Is your favorite ice cream flavor chocolate or vanilla?               Chocolate
Do you like morning or night?                                           Morning
                                                                      ...
What do you think is the hardest major at UIUC?                         Math+CS
Who is your favorite music artist?                                  My roommate
What's your favorite social media app?                                   WeChat
What is your favorite game to play (either video game or IRL)?    Honor of King
Where is your dream vacation spot?                                  New zealand
Name: 485, Length: 160, dtype: object

### 🔬 Test Case Checkpoint 🔬

In [56]:
## == PUZZLE 1.2 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('my_row' in vars()), "Your series should be named `my_row`."
assert(type(my_row) == pd.core.series.Series), "Make sure you've correctly converted your one-row DataFrame into a Series..."
assert(my_row.to_frame().T.equals(pd.DataFrame(df_me, dtype = 'O'))), "Make sure my_row corresponds to your row in df"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Choosing Your Columns

Before we begin, we have to think about our approach to finding your DISCOVERY twin.

You may have noticed our Hello Dataset has **more than 100 questions**. Instead of finding the most similar person to you using **every question**, we'll pick out a few questions to analyze that we think will do the best job at finding your twin! 

**But first, we need to revisit the questions.**

Recall the function `df.columns.tolist()`. To recap, this command will list **all of the columns** (in this case, our questions) in a DataFrame.

Use `df.columns.tolist()` in the cell below. 

<br>

**Viewing the Full Output**: When you do that, you will likely see the message:

> Output exceeds the __size limit__. Open the full output data __in a text editor__.

If you do, click the **in a text editor** link to open the whole list in a new tab of VSCode.

In [57]:
df.columns.tolist()

['Name',
 'Lab',
 'When flipping a coin, heads or tails?',
 'Is your favorite ice cream flavor chocolate or vanilla?',
 'Do you like morning or night?',
 'Is your favorite number even or odd?',
 'Do you have a pet?',
 'Do you prefer summer or winter?',
 'Are you in the Gies College of Business?',
 'Do you prefer Movies or TV shows?',
 'Do you prefer pizza or hamburgers?',
 'You describe yourself as:',
 'Do you prefer sweet or salty food?',
 'Do you eat breakfast?',
 'Do you speak a second language?',
 'Do you prefer cats or dogs?',
 'Do you prefer Italian or Mexican food?',
 'Cookies or Brownies?',
 'Do you like apples or bananas?',
 'Waffles or pancakes?',
 'Night Owl or Early Bird?',
 'Did you do high school in Illinois?',
 'Do you typically shower in the morning or at night?',
 'Do you prefer sweet or savory food?',
 'What month is your birthday?',
 'Do you use a Mac or Windows Laptop?',
 'Do you like pizza or pasta?',
 'Do you wear glasses?',
 'Fall or spring season?',
 'Do you prefer pink or blue?',
 'Does your UIN end with an even or odd number?',
 'Do you use corrective lenses (contacts/glasses)?',
 'Do you prefer Apple Music or Spotify?',
 'Do you have any siblings?',
 'Are you from Chicago?',
 'Pick a number: One or Two.',
 'Do you prefer basketball or football?',
 'Do you prefer the beach or mountains?',
 'Do you prefer breakfast or dinner?',
 'Do you prefer Coca Cola or Pepsi?',
 'Do you prefer coffee or tea?',
 'Are you an extrovert or introvert?',
 'Do you prefer hotdogs or hamburgers?',
 'Do you like Messi or Ronaldo?',
 'Have you ever been outside of United States?',
 'Do you have more than 1 sibling?',
 'Does pineapple belong on pizza?',
 'Do you live in Urbana or Champaign?',
 'Do you prefer sunny or rainy days?',
 'Red or Blue?',
 'Is your DISCOVERY lab the last class of your day?',
 'Have you had your 19th birthday?',
 'Are you a Statistics Major?',
 'Are you currently wearing shorts?',
 'Are you from Chicago or the suburbs?',
 'Are you registered for the 9am or 11am lecture?',
 'Are you team Edward or team Jacob?',
 'Cold Coffee or Hot Coffee?',
 'Did you go to the football game against WIU?',
 'Cookies or Ice Cream?',
 'Do you prefer urban or rural areas?',
 'Do you prefer creamy or chunky peanut butter?',
 'Dunkin or Starbucks?',
 'Football or soccer?',
 'Fruits or vegetables?',
 'Do you prefer gold or silver jewelry?',
 'Do you prefer hot or cold weather?',
 'Do you prefer in person or online classes?',
 'Do you prefer Instagram Reels or TikTok?',
 'Do you prefer Kendrick Lamar or Drake?',
 'Do you prefer ketchup or honey mustard?',
 'Do you prefer Lebron James or Michael Jordan?',
 'Do you eat beef?',
 'Do you exercise regularly?',
 'Do you game on a PC or Console?',
 'Do you have a brother?',
 'Do you prefer being hot or cold?',
 'Do you like chocolate ice cream?',
 'Do you like cilantro or not?',
 'Do you prefer DC or Marvel?',
 'Do you like ice cream?',
 'Do you like Mint Chocolate Chip ice cream?',
 'Do you like pizza?',
 'Red or Green?',
 'Do you like running?',
 'Do you like school?',
 'Sweet food or spicy food?',
 'Do you live in a dorm or apartment?',
 'Do you live in University Housing or Private Housing?',
 'Do you prefer Xbox or Playstation?',
 'Do you prefer travelling by plane or cruise?',
 'Breakfast or Lunch?',
 'Do you prefer lunch or dinner?',
 'Do you prefer mild or spicy food?',
 'Nike or Adidas?',
 'Do you prefer pens or pencils?',
 'Purple or orange?',
 'Red or Black?',
 'Sausage or Bacon?',
 'Skittles or M&Ms?',
 'Soup or Salad?',
 'Chicken or steak?',
 'Tacos or Burritos?',
 'Do you prefer the window or aisle seat on an airplane?',
 'TikTok or Instagram?',
 'Do you prefer to work remotely or in office?',
 'What comes first, milk or cereal?',
 'Do to typically go to bed before or after 11pm?',
 'How should toilet paper be rolled?',
 'Have you eaten lunch today?',
 'Headphones or Earbuds?',
 'If you had to go to sleep at the same time every night, would it be ...',
 'Is a hot dog a sandwich?',
 'Is a tomato a fruit or a vegetable?',
 'Is Apple better than Android?',
 'Is Tuesday or Wednesday better?',
 'Is your birth date odd or even?',
 'Is your birth MONTH even or odd?',
 'Is your birthday in the first fifteen days of the month?',
 'Matcha or Coffee?',
 'Hoodie + Shorts or Shirt + Pants?',
 'Noodles or Rice?',
 'Savory or sweet breakfast?',
 'Was Illinois Your Dream School?',
 'Sights and Sounds: Were you Orange or Blue?',
 'Seals or Penguins?',
 'Orange or Blue?',
 'Soda or Juice?',
 'North Pole or South Pole?',
 'Prefer Lecture of Lab in DISCOVERY?',
 'Computer Science or Statistics?',
 'Do you prefer Mom or Dad?',
 'Would you rather be Courageous Pizza or Honest Broccoli?',
 'Would you rather be too hot or too cold?',
 'When do you go to the gym?',
 'Orange or Apple?',
 "Would you rather know how you die or know when you'd die?",
 'Which of the following descriptions best matches your favorite movie?',
 'Is math red or blue?',
 'Do you get closer to 6 or 7 hours of sleep?',
 'How many classes are you taking this semester?',
 'How many credit hours are you taking?',
 'How many hours do you sleep in a night?',
 'How many siblings do you have?',
 'Pick a number between 1 and 10.',
 'What is your shoe size (US size)?',
 'How many cups (8 oz.) of water do you drink a day?',
 'What number do you consider as an unlucky number?',
 'How many people is the ideal number of people at a party?',
 'What is your phone battery percentage currently at?',
 'Besides the US, what country would you like to live in?',
 'What is your favorite color?',
 'Favorite way to spend your free time?',
 'What genre of music do you like the most?',
 'If you were an animal, which would you be? / What is your spirit animal?',
 'What do you think is the hardest major at UIUC?',
 'Who is your favorite music artist?',
 "What's your favorite social media app?",
 'What is your favorite game to play (either video game or IRL)?',
 'Where is your dream vacation spot?']

### Puzzle 1.3: Choosing Your Columns
From the above list of **columns** (questions), choose **at least 12 questions** to work with moving forward. Please use **only questions with binary answers** for this part of the analysis :) 

***Make sure to choose the questions intentionally! You'll want to pick questions you find interesting and questions that you think would best measure the similarity between 2 people (don't just pick the first 12 questions).***

These will be the questions used to **calculate your similarity** to other people in DISCOVERY! Feel free to include more if you'd like. 

Store them as a **list** of **strings** named `questions` in the Python cell below:

In [58]:
questions = [
    "When flipping a coin, heads or tails?",
    "Is your favorite ice cream flavor chocolate or vanilla?",
    "Do you like morning or night?",
    "Is your favorite number even or odd?", 
    "Do you have a pet?",
    "Do you prefer summer or winter?",
    "Do you prefer Movies or TV shows?",
    "Do you prefer pizza or hamburgers?",
    "Do you prefer sweet or salty food?",
    "Do you speak a second language?",
    "Do you prefer cats or dogs?",
    "Do you prefer Italian or Mexican food?",
    "Cookies or Brownies?",
    "Do you like apples or bananas?",
    "Waffles or pancakes?",
    "Night Owl or Early Bird?",
    "Do you typically shower in the morning or at night?"]

### 🔬 Test Case Checkpoint 🔬

In [59]:
## == PUZZLE 1.3 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('questions' in vars()), "Please name your list of questions `questions`."
assert(type(questions) == list and type(questions[0]) == str), "Make sure your `questions` variable is a list of strings."
assert(len(questions) >= 12), "Do you have at least 12 questions in your columns list?"
for q in questions:
   assert(q in df), f"\"{q}\" not in columns of `df`. Double check that you've copied each question correctly. The question texts should match up EXACTLY with the output from `df.columns.to_list()`."
for q in questions:
   assert(len(df[q].value_counts()) == 2), "Make sure that you've only included questions with binary answers in your columns list."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 2: The Similarity Function

Now that we have chosen the **questions** we'd like to evaluate, it's time to create a **function** to calculate a similarity value for each person, or each row in `df`.

In lecture, you learned that a Python **function** takes an **input** in and **returns** a **value**. 

For this specific function, we will take a **row** and calculate a **similarity score** for that row.

But first, **print your list of questions** using the Python cell below for reference:

In [60]:
print(questions)

['When flipping a coin, heads or tails?', 'Is your favorite ice cream flavor chocolate or vanilla?', 'Do you like morning or night?', 'Is your favorite number even or odd?', 'Do you have a pet?', 'Do you prefer summer or winter?', 'Do you prefer Movies or TV shows?', 'Do you prefer pizza or hamburgers?', 'Do you prefer sweet or salty food?', 'Do you speak a second language?', 'Do you prefer cats or dogs?', 'Do you prefer Italian or Mexican food?', 'Cookies or Brownies?', 'Do you like apples or bananas?', 'Waffles or pancakes?', 'Night Owl or Early Bird?', 'Do you typically shower in the morning or at night?']

### Puzzle 2.1: The Similarity Function

In the code below, you will find an outline for a `similarity` function that returns a similarity score:

> ```py
> def similarity(row):
>     # This function will keep track of a `score` of how similar two rows are with each other.
>     # The score begins at zero and we will add to it every time a row matches.
>     score = 0 
> 
>     # This if statement below checks to see if the `row` shares your choice between Coffee and Tea
>     # - If the values are the same (==), we add one to the score.
>     # - If the values are NOT the same, the `score = score + 1` line is skipped.
>     if row["Coffee or Tea?"] == my_row["Coffee or Tea?"]:
>         score = score + 1
>
>     # Finally, return the `score`.
>     # ...this line (the return statement) should always be the LAST line. 
>     return score
> ```

Using this same function structure, complete your `similarity` function below **using the questions you picked out earlier**.  This will require you to write **one if statement** for each question you selected:

In [61]:
def similarity(row):
    # Your Task Here:
    # Repeat the above syntax many times for EACH question (column) that you have chosen in your list
    # IMPORTANT: Make sure to keep your lines all at this same level of tabbing out from the start.    
    # ALSO IMPORTANT: Delete or the replace the "Coffee or Tea?" question!
    #                 (unless you've decided that is one of your evaluating questions). 
    
    score = (row[questions] == my_row[questions]).sum()


    ...

    return score

### 🔬 Test Case Checkpoint 🔬

In [62]:
## == PUZZLE 2.1 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(similarity(my_row) == len(questions) or similarity(my_row) == my_row[questions].count()), "Ensure you've added all the questions from your list and ONLY questions from your list correctly to your similarity function."
assert( len(df.apply(similarity, axis = 1).unique()) > 2 ), "Your function must return differnet values for differnet rows."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 2.2: Applying the Similarity Function
Now that you've properly defined the similarity function, we need to **apply** it to the rest of the Hello Dataset DataFrame so we can produce a **similarity score** for each person who took the survey!

Using the above explanation as reference, **add a column** named `Similarity Score` to your original DataFrame that contains the value after running your similarity function you defined earlier across all rows:

(Hint): Look back to `lab_illini` part 2.2 & `lab_gpa` part 1.1

In [63]:
df["Similarity Score"] = df.apply(similarity, axis=1)

### 🔬 Test Case Checkpoint 🔬

In [64]:
## == PUZZLE 2.2 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('Similarity Score' in df), "Make sure you've named and added the Similarity Score column to your original df."
assert(df['Similarity Score'].dtype == 'int64'), "Double check that you've called the similarity function correctly in your df.apply()."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 3: Finding your Twin(s)

Your last column `Similarity Score` in `df` is now a metric (a measurement) of how **similar** you are to everyone else in the class, based on the **questions you've chosen**!

Finally, we can do analytical Data Science!

### Puzzle 3.1: Your Twin in 107

Using the Python cell below, find the **person most similar to you in the entire course**. Think about how you would do this using the `Similarity Score` column.

Note that **you should be most similar to yourself** (you will always match yourself)! This is not the right answer. Find the person with the highest score ***aside from yourself***. *(There is a chance there can be multiple people tied as the person most similar to you and that's okay!)*

Make sure to display the rows.

In [65]:

tiwn =df.nlargest(5, 'Similarity Score')
tiwn

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
485,yes！,Y27,Heads,Chocolate,Morning,Even,Yes,Winter,Not in Gies,TV Shows,...,gray,play mobile game,Jazz,Panda,Math+CS,My roommate,WeChat,Honor of King,New zealand,17
28,Sophia,Y26,Heads,Chocolate,Morning,Odd,Yes,Winter,Not in Gies,Movies,...,Yellow,Reading,2000’s,Whale shark,Computer Science,Billy Joel,Instagram,Mahjong,Santorini,15
340,Mayte,Y31,Heads,Chocolate,Night,Even,Yes,Winter,Not in Gies,TV Shows,...,Blue,with family/friends or working out,Music of Latin America,a golden doodle,Engineering,Drake,Tiktok,Mario Kart,Hawaii,15
24,Amanda,Y29,Heads,Chocolate,Night,Odd,Yes,Winter,In Gies College of Business,TV Shows,...,Black,On tiktok,Pop,Panda,Bio chemical engineering,$uicide boy$,Tiktok,Puzzles,Haiti,14
121,Chang,Y35,Heads,Chocolate,Night,Even,Yes,Winter,Not in Gies,Movies,...,black,play games,minyao,lizard,CS,zhaolei,Wechat,DBD,US,14

### Puzzle 3.2: Your Lab Twin

Now, chances are your twin isn't in your lab section. Because we conveniently have our row, `Similarity Score` applied to the **entire** set of responses to the survey, we can create smaller DataFrames to answer more questions. 

We want to find the person most similar to you in **your lab section**, otherwise known as your lab twin! We can create a new DataFrame to answer this question. 

However, some of your CAs and TAs, who are part of your lab section, are in more than one lab section! Those who have multiple sections have `Y##, Y##...` in their Sections column. How can we create a DataFrame that includes the CAs and TAs who are in more than one lab section? Python saves the day again.

#### **The `contains` Function**
In Python, the `contains` function can be used to check if a specific **substring** is present in a **string**. 

This will come in handy for us, because we can see if `Y##` is in the **names** of any rows in our DataFrame.

Using the `contains` function, create a **new DataFrame** with everyone in your lab section: `df_section`. Part of the statement has been completed for you to show you how to use `contains`. Complete it and make sure to display the dataframe.

*Note that we have to cast our `Lab` column of `df` to a **string** by using `.str`.

*Second note: the `na=False` parameter in the `contains` function makes it so that we ignore the rows with no lab section.

In [66]:
df_section = df[(df['Lab'].str.contains("Y27",na=False))]
df_section

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
14,Swara,Y27,Heads,Vanilla,Night,Odd,No,Winter,Not in Gies,Movies,...,Purple,Going out,Pop,Penguin,Engineering,Laufey,Instagram,Uno,Greece,6
30,Katie,Y27,Heads,Chocolate,Morning,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Purple,Shopping,Pop,Dog,Computer Science,Noah Kahan,TikTok,Clue,Croatia,11
193,Nao,Y27,Tails,Chocolate,Night,Even,Yes,Winter,Not in Gies,Movies,...,Pink,hanging out with friends,rap,Meerkat,Computer Science,Childish Gambino,TikTok,stress (card game),Shang hi,10
219,Darsh,Y27,Tails,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,Blue,Scroll through Tiktok,Rap,Dog,Electrical engineering,Drake,Tiktok,Clash Royale,Monaco,8
226,Arnav,Y27,Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Orange,Watching movies,Pop,Capybara,ChemE,Queen,Twitter,Soccer,Munich,8
271,Andrew,Y27,Tails,Vanilla,Morning,Odd,Yes,Summer,Not in Gies,TV Shows,...,blue,play basketball,rap,fox,premed,daniel caesar,tiktok,basketball,japan,8
275,Miguel,Y27,Heads,Vanilla,Night,Even,No,Summer,Not in Gies,TV Shows,...,Green,Volleyball,Pop,Owl,Computer Engineeriing,Frank Sinatra,Instagram,Roblox,Maldives,6
327,Nate,Y27,Tails,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Green,Hanging out with friends,Country,Cow,CS,Luke Combs,TikTok,MLB the Show,Hawaii,8
341,Ryan,Y27,Tails,Vanilla,Night,Even,No,Summer,Not in Gies,TV Shows,...,Green,Basketball,Rap,Lion,Business,Drake,Instagram,Fortnite,Japan,9
361,Elisha,Y27,Tails,Chocolate,Morning,Odd,Yes,Winter,Not in Gies,TV Shows,...,purple,rotting,kpop,cat,CS,ARTMS,twitter,skyrim,south korea,14
363,Mino,Y27,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Blue,Fishing,Alternative Rock,Flathead Catfish,Electrical Engineering,The Verve,Youtube,Hill Climb Racing 2,Lodge next to a well-stocked lake in the deep ...,7
453,Prateek,Y27,Heads,Vanilla,Night,Odd,No,Winter,Not in Gies,Movies,...,black,Video Games,Pop,Dog,Aerospace Engineeering,Drake,instagram,Cricket,Switzerland,9
485,yes！,Y27,Heads,Chocolate,Morning,Even,Yes,Winter,Not in Gies,TV Shows,...,gray,play mobile game,Jazz,Panda,Math+CS,My roommate,WeChat,Honor of King,New zealand,17
527,Payton,Y27,Tails,Chocolate,Night,Odd,Yes,Summer,Not in Gies,TV Shows,...,Blue,Sleeping,Alternative,Peacock,Engineering,"Tyler, the Creator",TikTok,Fortnite,Canada,9
537,Osama,Y27,Heads,NaN,Night,Odd,No,Summer,In Gies College of Business,Movies,...,Black or Red,Making Money,Rap or R&B,Lion,Anything to do with Medicine,Nipsey Hussle or Mo3,Don't Have one,Hide and Seek,Mecca,7
557,Berra,Y27,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Blue,With friends,Indie,Red Panda,Computer Science,Dominic Fike,TikTok,Roblox,Southern Italy,9
584,Vikramaditya,Y27,Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Green,Gooning,R&B,Lion,Sociology,Beabadobee,Tiktok,Soccer,Cancun,10
586,Daryl,Y27,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Black,sleeping,Afrobeats,Tiger,Engineering,Davido,Tiktok,Farcry,Bahamas,8
607,Nirmit,Y27,Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,Movies,...,blue,bed,rap,unicorn,CS,netspend,tiktok,roblox,Switzerland,8
615,Alex,Y27,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Blue,With Friends,Pop Music,Penguin,Electrical Engineering,Jay Chou,Instagram,Football Manager,Beaches,9
632,Syafino,Y27,Heads,Vanilla,Morning,Even,Yes,Winter,Not in Gies,TV Shows,...,blue,gym,pop,cat,comp eng,idk,instagram,csgo,greece,11
670,Yashfeen,Y27,Heads,Vanilla,Night,Odd,No,Summer,In Gies College of Business,TV Shows,...,Pink,Hanging out with friends,Rap,Unicorn,Engineering,Billie Eilish,Snapchat,Solitaire,Maldives,8
770,Ady,Y27,Heads,Vanilla,Morning,Even,Yes,Summer,In Gies College of Business,TV Shows,...,Blue,hanging out with friends,Country,otter,chemistry,Old Dominion,snapchat,pickleball,Hawaii,10
821,Ari,Y27,Heads,Chocolate,Morning,Odd,No,Winter,Not in Gies,TV Shows,...,Blue,Working out,Indie Pop,Lion,Engineering,TTC,Tiktok,Poker,Hawaii,11
861,Joy,Y27,Tails,Chocolate,Night,Even,No,Winter,In Gies College of Business,Movies,...,blue,stay at home,popular music,dog,cs,Taylor Swift,red note,Teamfight Tactics,Japan,10
940,Tian,Y27,Heads,Chocolate,Morning,Odd,No,Summer,Not in Gies,Movies,...,Blue,Playing basketall,Pop,Panda/yes,Computer Science,Jay Chou,Tiktok,CS2,Beach,10
956,Kenny,Y27,Heads,Chocolate,Morning,Even,No,Summer,Not in Gies,Movies,...,Red,Gym or soccer,Rap,Dog,Grainger CS,The Weeknd,Tiktok,Soccer or Football,Bahamas,10
973,David,Y27,Heads,Chocolate,Night,Even,No,Summer,In Gies College of Business,Movies,...,Green,gym,polish,squierrel,cs,drake,snapchat,clash royale,hawaii,9
1096,CA Emily,"Y22, Y27",Heads,Chocolate,Night,Even,Yes,Winter,Not in Gies,Movies,...,pink,With friends,hip hop,Cheetah,ECE,Noah Kahan,instagram,minecraft,Europe,11
1107,CA Caroline,Y07 Y27,Heads,Vanilla,Night,Odd,No,Summer,In Gies College of Business,Movies,...,blue,With friends,Country,Monkey,Computer Science,Treaty Oak Revival,Instagram,Soccer,Italy,7
1156,Winona,Y27,Heads,Chocolate,Night,Even,Yes,Winter,In Gies College of Business,TV Shows,...,blue,Watch movie,pop,dog,engineering,laufey,instagram,nonogram,tokyo,12

### Puzzle 3.3: Your Lab Twin!

Similarly to Puzzle 3.1, find your lab section twin. Make sure to display the dataframe.

In [67]:

labtwin = df_section.nlargest(20, "Similarity Score")
labtwin

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
485,yes！,Y27,Heads,Chocolate,Morning,Even,Yes,Winter,Not in Gies,TV Shows,...,gray,play mobile game,Jazz,Panda,Math+CS,My roommate,WeChat,Honor of King,New zealand,17
361,Elisha,Y27,Tails,Chocolate,Morning,Odd,Yes,Winter,Not in Gies,TV Shows,...,purple,rotting,kpop,cat,CS,ARTMS,twitter,skyrim,south korea,14
1156,Winona,Y27,Heads,Chocolate,Night,Even,Yes,Winter,In Gies College of Business,TV Shows,...,blue,Watch movie,pop,dog,engineering,laufey,instagram,nonogram,tokyo,12
30,Katie,Y27,Heads,Chocolate,Morning,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Purple,Shopping,Pop,Dog,Computer Science,Noah Kahan,TikTok,Clue,Croatia,11
632,Syafino,Y27,Heads,Vanilla,Morning,Even,Yes,Winter,Not in Gies,TV Shows,...,blue,gym,pop,cat,comp eng,idk,instagram,csgo,greece,11
821,Ari,Y27,Heads,Chocolate,Morning,Odd,No,Winter,Not in Gies,TV Shows,...,Blue,Working out,Indie Pop,Lion,Engineering,TTC,Tiktok,Poker,Hawaii,11
1096,CA Emily,"Y22, Y27",Heads,Chocolate,Night,Even,Yes,Winter,Not in Gies,Movies,...,pink,With friends,hip hop,Cheetah,ECE,Noah Kahan,instagram,minecraft,Europe,11
193,Nao,Y27,Tails,Chocolate,Night,Even,Yes,Winter,Not in Gies,Movies,...,Pink,hanging out with friends,rap,Meerkat,Computer Science,Childish Gambino,TikTok,stress (card game),Shang hi,10
584,Vikramaditya,Y27,Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Green,Gooning,R&B,Lion,Sociology,Beabadobee,Tiktok,Soccer,Cancun,10
770,Ady,Y27,Heads,Vanilla,Morning,Even,Yes,Summer,In Gies College of Business,TV Shows,...,Blue,hanging out with friends,Country,otter,chemistry,Old Dominion,snapchat,pickleball,Hawaii,10
861,Joy,Y27,Tails,Chocolate,Night,Even,No,Winter,In Gies College of Business,Movies,...,blue,stay at home,popular music,dog,cs,Taylor Swift,red note,Teamfight Tactics,Japan,10
940,Tian,Y27,Heads,Chocolate,Morning,Odd,No,Summer,Not in Gies,Movies,...,Blue,Playing basketall,Pop,Panda/yes,Computer Science,Jay Chou,Tiktok,CS2,Beach,10
956,Kenny,Y27,Heads,Chocolate,Morning,Even,No,Summer,Not in Gies,Movies,...,Red,Gym or soccer,Rap,Dog,Grainger CS,The Weeknd,Tiktok,Soccer or Football,Bahamas,10
341,Ryan,Y27,Tails,Vanilla,Night,Even,No,Summer,Not in Gies,TV Shows,...,Green,Basketball,Rap,Lion,Business,Drake,Instagram,Fortnite,Japan,9
453,Prateek,Y27,Heads,Vanilla,Night,Odd,No,Winter,Not in Gies,Movies,...,black,Video Games,Pop,Dog,Aerospace Engineeering,Drake,instagram,Cricket,Switzerland,9
527,Payton,Y27,Tails,Chocolate,Night,Odd,Yes,Summer,Not in Gies,TV Shows,...,Blue,Sleeping,Alternative,Peacock,Engineering,"Tyler, the Creator",TikTok,Fortnite,Canada,9
557,Berra,Y27,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Blue,With friends,Indie,Red Panda,Computer Science,Dominic Fike,TikTok,Roblox,Southern Italy,9
615,Alex,Y27,Heads,Chocolate,Night,Even,No,Summer,Not in Gies,TV Shows,...,Blue,With Friends,Pop Music,Penguin,Electrical Engineering,Jay Chou,Instagram,Football Manager,Beaches,9
973,David,Y27,Heads,Chocolate,Night,Even,No,Summer,In Gies College of Business,Movies,...,Green,gym,polish,squierrel,cs,drake,snapchat,clash royale,hawaii,9
219,Darsh,Y27,Tails,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,Blue,Scroll through Tiktok,Rap,Dog,Electrical engineering,Drake,Tiktok,Clash Royale,Monaco,8

#### **➡️ Once you have that person, follow your TAs directions!<br> ➡️ They will tell you when to complete the rest of Puzzle 3.3**<br>

Help them get up to this point in the lab and let them find their DISCOVERY twin!  *(Are you twins of each other?)* 

➡️ Once you are **BOTH** to this section, introduce yourself and your DISCOVERY lab section "twin" to your lab TA. <br>
➡️ Make sure you know what your "Similarity Score" to your twin is! <br>
➡️ If you do this introduction to your TA **in-person during your lab section, you will earn +1 EC**! :)

Note that there may be ties in `Similarity Score` due to the usage of only parts of the dataset. If you're curious, you can go back and **add more questions** to your `questions` list and `similarity(row)` function, rerunning the code to have more evaluative similarity scores.

### Puzzle 3.4: The Course Staff
A lot of wonderful course staff work together to bring you all the content for Data Science DISCOVERY. 

The course staff of 107 consists of the **Professors, TAs, and CAs**. As you saw in the previous parts, they've all completed the Hello Survey too! 

Their response under the `Name` column is standardized and follows these formats:
- `Prof. [Name]`,
- `TA [Name]`, or
- `CA [Name]`

The `contains` function will come in handy for us once again, because we can see if `"CA "`, `"TA "`, or `"Prof. "` is in the **names** of any rows in our DataFrame.

Using the `contains` function, create a **new DataFrame** with just the course staff: `df_staff`, and display the dataframe. 

Read the following guide on **using `contains` to select all rows based on String contents**: https://discovery.cs.illinois.edu/guides/DataFrame-Row-Selection/dataframe-string-contains/

*Note that we have to cast our `Name` column of `df` to a **string** by using `.str`.

In [68]:
# IMPORTANT: Make sure you include a whitespace in 'CA ' and 'TA ' so that people with those
# #          letters in their name aren't included.  Whitespace matters! :)

df_staff = df[df["Name"].astype(str).str.contains("Prof",na=False)|df["Name"].astype(str).str.contains("CA",na=False)|df["Name"].astype(str).str.contains("TA",na=False)]

df_staff

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
0,Prof. Wade,AL1,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin,9
1,Prof. Karle,AL1,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives,9
120,TA Tyler,"Y06, Y10",Tails,Chocolate,Night,Even,No,Winter,Not in Gies,TV Shows,...,Orange,Playing Terraria,Pop rock,Tardigrade,Chemical Engineering,Billy Joel,Reddit,Terraria,NaN,8
220,CA Lyndsey,"Y06, Y25",Heads,Chocolate,Night,Odd,Yes,Summer,Not in Gies,Movies,...,Red,With my dogs,Pop,Deer,Computer engineering,Gracie Abrams,Instagram,Jackbox,Italy,9
269,CA Ona,"Y20, Y23",Heads,Vanilla,Morning,Odd,No,Summer,Not in Gies,TV Shows,...,Blue,TikTok,Rock,Cat,Engineering,Hozier,TikTok,Clue,Iceland,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,TA Jackson,Y29 Y36,Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,TV Shows,...,Red,Research,Metal,Penguin,Art,Les Claypool,Reddit,Sea of Thieves,Italy,8
1164,CA Jaythan,"Y11, Y26",Heads,Vanilla,Night,Odd,Yes,Winter,In Gies College of Business,Movies,...,Black,Hanging with Friends,Mexican Regional,Penguin,Bioengineering,Peso Pluma,Instagram,Marvel Rivals,Paris,7
1176,CA Lara,"Y24, Y33, Y40",Heads,Chocolate,Night,Even,No,Winter,Not in Gies,Movies,...,Light teal,Reading,Shoegaze,Mayfly,Physics,Marina,Reddit,Minds Beneath Us,Japan,9
1197,CA Emma,Y20,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Green,Crocheting,Pop,Frog,Computer Science,Lady Gaga,TikTok,Minecraft,Italy,8
1198,CA Soph,Y01 Y14 Y15 Y18,Heads,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Red,Relaxing,Hyperpop,Rabbit,Aerospace Engineering,Ayesha Erotica,Pinterest,Twister,Mexico City,9

### 🔬 Test Case Checkpoint 🔬

In [69]:
## == PUZZLE 3.3 TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('df_staff' in vars()), "Your DataFrame of course staff should be named 'df_staff'."
assert(len(df_staff) == 67), "Check you've added all the course staff correctly."
assert(len(df_staff.columns.to_list()) == 161), "You should have all of the questions columns and the Similarity Score column in df_staff." 

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 3.5: Course Staff Twin!

Now that we have the course staff responses in `df_staff`, find your course staff twin (the staff member who has the **highest Similarity Score** to you) and display it.

In [70]:
top_two_staff = df_staff.nlargest(2, "Similarity Score")
top_two_staff

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?,Similarity Score
1136,CA Bella B,Y05 Y16 Y32,Heads,Chocolate,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,purple,run,pop,butterfly,cheme,sabrina carpenter,tiktok,orangatang,Italy,14
1117,TA Erik,"Y15, Y21",Heads,Vanilla,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,blue (#1d4ed8),Driving,Indie pop,Dog,ECE,Keshi,Instagram,Escape from Tarkov,Switzerland,12

### Analysis: Final Reflection

**Question 1:** Is it possible that the person that you found as your STAT107 "twin" may not find you as their twin? Explain your answer.

**Question 2:** Do you think the method we used to find similar people is effective? Explain why or why not and give at least one suggestion to improve it.

Q1:It's possible I think. This can happen because the method for finding similar people depends on the attributes or criteria used, and those criteria might not be symmetric.
Q2:Yeah,it's effective! if the dataset is limited or if certain traits are weighted equally when they shouldn’t be.

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)